version: '3.1'

networks:
  unpubd:
    driver: bridge

volumes:
  mongodata: null

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodata:/data/db
      # -  PATH_TO_INITDB#:/docker-entrypoint-initdb.d/
    networks:
      - unpubd
    # use if we need to connect directly to Mongo from host. ONLY FOR TESTING
    #    ports:
    #      - 27017:27017      

    logging:
      driver: "local"

  unpubd:
    container_name: unpubd
    image: noojee/unpubd:latest
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      UNPUBD_PORT: ${UNPUBD_PORT}
      TZ: ${TZ}
    links:
      - mongodb
    networks:
      - unpubd
    ports:
      - ${UNPUBD_PORT}:${UNPUBD_PORT}
    logging:
      driver: "local"
